name = "Gherkin"
grammar = "ghkerin"
path_suffixes = ["feature", "gherkin"]
line_comments = ["#"]
autoclose_before = ";:.,=}])>"
brackets = [
    { start = "\"", end = "\"", close = true, newline = false, not_in = [
        "string",
        "comment",
    ] },
]
tab_size = 2
